### ISSUE TITLE
"ReleaseForRunning" bundle identifier not set for imessagestickers target

### ISSUE THREAD

**Issue by M0rph3v5** [agens-no/iMessageStickerUnity#10]
When generating the xcode project and trying to run it I came across this, it's fixable by adding the bundle identifier to the ReleaseForRunning and ReleaseForProfling which is something that unity nowadays generates? 

Anyway after that I get a different error:

> error: Couldn't load Info dictionary for <DVTFilePath:0x7f8266f7d8c0:'/Users/.../ReleaseForRunning-iphoneos/game.app/PlugIns/Unity-iPhone-Stickers.appex'

I'm not sure if it's related or not, any ideas?

**Comment by M0rph3v5** [comment]
Okay, that's because the info.plist is missing in the copy bundle resources of the stickers target. When that is added I get the following error:

> Embedded binary's bundle identifier is not prefixed with the parent app's bundle identifier.

**Comment by M0rph3v5** [comment]
I think you cannot have the stickers plist be also named info.plist. It needs a different name, renaming it fixed it.

**Comment by M0rph3v5** [comment]
Okay, ignore all of above. It all comes down to this:

1. The $(PRODUCT_BUNDLE_IDENTIFIER) does not resolve, which in turn makes the info.plist be 'invalid' according to xcode. I've modified the StickersExport.cs to just enter the full bundle id of the added target there.

2. If you're generating for release, unity adds 2 build configs 'ReleaseForProfiling' and 'ReleaseForRunning'. Which means the bundle id is not set for those in the stickers target case.

**Comment by skjalgsm** [comment]
Could you make a PR with your changes please?

**Comment by M0rph3v5** [comment]
Haven't quite fixed #2 yet, I'll make a pr when I get the chance.

**Comment by trongthien18** [comment]
Hello,
Your plugin is really cool. I'm working on the automation build system and I really need it. But I have the same problem, and the project can not build. 
Waiting for your fixing.

**Comment by M0rph3v5** [comment]
@trongthien18 I'm running into unity cloud build issues now as well if that's what you mean. The cloud build team is looking into it, seems like a partial issue on their end (aside from the fixes I've done so far)

**Comment by skjalgsm** [comment]
ReleaseForRunning and ReleaseForProfiling is now set. Any other problems then you should open another issue. Thank you so much for reporting these

**Comment by M0rph3v5** [comment]
thanks for fixing it, it seems like you're missing something for those targets. Have you tested it?

I'm getting the following error now:

> ReleaseForRunning-iphoneos/Unity-iPhone-Stickers.appex: No such file or directory

**Comment by skjalgsm** [comment]
Yeah it works here :S

**Comment by M0rph3v5** [comment]
Let me look into it further, maybe related to firebase generating a workspace. Not sure. I'll report back.

**Comment by M0rph3v5** [comment]
if I check 'Copy only when installing' under the main target -> build phases -> embed app extensions. it works. Not sure if that's checked with your project? Wasn't with mine.

**Comment by M0rph3v5** [comment]
which unfortunately only works for building to your device, not for archiving production builds :(

**Comment by M0rph3v5** [comment]
Adding the stickers target as a target dependency of the main project seems to fix the issue. Not sure your plugin does that and another plugin removed it perhaps?

**Comment by skjalgsm** [comment]
That should be taken care of in this plugin, yes.

**Comment by Josk** [comment]
Hi We have the same problem here, the sticker pack is not added as a target dependency of the main target. What is the code that is should take care of it?

**Comment by tobytaro** [comment]
@M0rph3v5 hi, I got the same error, may I  ask how to "Adding the stickers target as a target dependency of the main project"?

**Comment by M0rph3v5** [comment]
Go to build phases and then there’s a add target dependency thing. Hit + and the stickers thing will be there.

**Comment by tobytaro** [comment]
@M0rph3v5 Thanks! It works. But every time I build from unity, this target dependency gone. I need to manually add it again. Is it the problem from the plugin?
