### ISSUE TITLE
Unity 5.3 support

### ISSUE THREAD

**Issue by colinamuzo** [agens-no/iMessageStickerUnity#12]
Hi I tried using this plugin in Unity 5.3 and there were compile errors (which I fixed) and a bunch of null refs (StickerPackEditor.cs, line 446, 363).

Is there any point in me trying to get this working in Unity 5.3?  Or is there some fundamental, unfixable problem that I will eventually encounter?

Thanks.

Colin

**Comment by skjalgsm** [comment]
If you just fix the compile errors it should work fine. I'll make sure it
works for 5.3 as well now that I know someone needs it.

**Comment by colinamuzo** [comment]
That's great news, thank you.  Will you reply back on this thread when you have made it 5.3-compatible?

**Comment by skjalgsm** [comment]
Sure. Currently on holiday so might be a few weeks though

**Comment by colinamuzo** [comment]
Ok, no worries.

**Comment by skjalgsm** [comment]
Fixed the compile errors on 5.3 now. Please give it a try :)
