### ISSUE TITLE
Cloud build Unity failed

### ISSUE THREAD

**Issue by anhnguyenvn** [agens-no/iMessageStickerUnity#13]
Hello,

I am using your plugin in my project. Thank you so much for your useful plugin, it helps me a lot.
However I got an issue about building project with Unity Cloud Build. Here is the log:

16583:        [xcode] Check dependencies
16584:        [xcode] Unity-iPhone-Stickers has conflicting provisioning settings. Unity-iPhone-Stickers is automatically signed, but provisioning profile xxxxx-xxxxx-4083-9da1-65ba6360e337 has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor, or switch to manual signing in the project editor.
16585:        [xcode] Code signing is required for product type 'App Extension' in SDK 'iOS 10.3'
16586:        [xcode] ** ARCHIVE FAILED **
16587:        [xcode] The following build commands failed:
16588:        [xcode]   Check dependencies
16589:        [xcode] (1 failure)
16590: ! build of 'default-ios' failed. compile failed

I think I need to add manually the provisioning profile and provisioning profile specifier ( in sticker setting) Because in unity cloud build setting, the provisioning is added manually.

I have some concerns?
1. Do i need a new provisioning for sticker extension with new app id?
2. How can i get 2 values provisioning profile and provisioning profile specifier?

Thank you so much for your help, I do appreciate!

Regards,
Anh Nguyen

**Comment by skjalgsm** [comment]
Hi.

1. Yes
2. I dont use cloud build myself, how do you specify the provisioning
profile for the regular app now?

**Comment by anhnguyenvn** [comment]
Hi @Skjalgsm, thank for your reply

In Unity cloud build, I have only one option to specify a provisioning profile by uploading a provisioning *.mobileprovision and  certificate .p12 files. Those are for the main game. I don't know if there must be another *mobileprovision file for sticker extension or just need a provisioning defining a wildcard app id.

In the sticker settings inspector of your plugin, I saw 2 input fields for Provisioning Profile, and Provisioning Profile Specifier. Suppose that I have to make another  provisioning for extension as form of a .mobileprovision file, I don't know how to get those values: Provisioning Profile, and Provisioning Profile Specifier from that provisioning file. I don't have much experience with iOS stuff. Any advice on it?

And I also get a strange bug when my mono couldn't find definition of these 2: 
PlayerSettings.iOS.appleEnableAutomaticSigning and PlayerSettings.iOS.iOSManualProvisioningProfileID
I am using Unity 5.5.0f3. I have searched around but seem there's no one having the same issue.
Do you have any ideas why it happens?

Thank you so much!
Anh.

**Comment by skjalgsm** [comment]
I think I will contact unity cloud support and have a chat with them on how
to best resolve this. Uploadibg a wildcard provisioning file should work,
but you still need to input its name in the sticker pack inespector.

I'll look into the missing definitions. Unity rewrote some definitions back
and forth during 5.4 and 5.5, so my defines are probably not working for
that specific version 🙂

**Comment by anhnguyenvn** [comment]
Thank you so much for your reply, I also ask Unity about it. 
Is there a way that I can buy you a coffee ? :)

**Comment by SamiSdd** [comment]
Why this is closed? This is still an issue under Unity Cloud

**Comment by skjalgsm** [comment]
I apologize. I thought it was fixed as I made sure it worked in Unity 5.5.0f3

**Comment by SamiSdd** [comment]
I'm sure now that its relevant We're getting following error in unity cloud

No iOS profile matching 'H76AAAAAAA/Stickers Ad Hoc' found:  Xcode couldn't find a profile matching 'H76AAAAAAA/Stickers Ad Hoc'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the General tab of the target editor.

I've the following things setup.
1- Automatic Signing Turned Off
2- Provided GUID of Provisioning Profile in Provisioning Profile Textbox
3- Provided Name of Provisiioning Profile in 'Provisioning Profile Specifier' TextBox

With get the following error with following configuration
1- Automatic Signing Turned On

Provisioning profile "*** Ad Hoc" has app ID "com.big.game", which does not match the bundle ID "com.big.game.stickers".
[xcode] Provisioning profile "*** Ad Hoc" doesn't match the entitlements file's value for the application-identifier entitlement.

Please let me know if i'm doing anything wrong here. btw Both of these .mobileprovising is uploaded on UCB but i can select only one of them

**Comment by skjalgsm** [comment]
Hi.

I've been in contact with Unity. The reply I got was that 

> Cloud Build does not support multiple provisioning profiles currently.
> The development team are aware of this limitation and we are currently looking into a full solution for the future.

But there's also good news.

> The only workaround I can suggest at this time is to use a wildcard profile.

So specifically for you. You would need to go into developer.apple.com and into Certificates, Identifiers & Profiles. There you will need to generate a new app identifier that ends with a wildcard (*). Once you've done that you need to create a new provisioning profile for that new app identifier with a wildcard and use that in cloud build.

Please let me know if you have any questions.

**Comment by skjalgsm** [comment]
Closing this issue now as it has a work around and its not something this repo can fix.
