### ISSUE TITLE
[Feature Request] Adding Localization

### ISSUE THREAD

**Issue by sweatyc** [agens-no/iMessageStickerUnity#14]
First, thank for the great plugin that saved us lot of time!

I would like to request a feature on localization. Our app name is localized using [I2Localize](https://www.assetstore.unity3d.com/en/#!/content/14884), it would be great if the sticker app name can be localized too to match our main app name, in other language...

I'm not an iOS geek and I assume adding a group of InfoPlist.strings and Localizable.strings will do the job? Or even better, integrate with I2Localize and make all these automatic.

**Comment by skjalgsm** [comment]
This is something I am lacking myself, so it would be really nice, but it is beyond the scope of this plugin. I think that this is something that could be supported by the localization plugins instead. Especially considering that they probably already have the code for doing this.

**Comment by skjalgsm** [comment]
However, I will make an effort to add this functionality to the https://github.com/agens-no/PolyglotUnity plugin

**Comment by sweatyc** [comment]
Ok thanks, I also create [request](http://inter-illusion.com/forum/i2-localization/901-feature-request-localize-ios-sticker-app-name) in I2, hopefully it will be implemented and easy for him.
