### ISSUE TITLE
Do you have .unitypackage file?

### ISSUE THREAD

**Issue by alamops** [agens-no/iMessageStickerUnity#16]
Do you have .unitypackage file to download?

**Comment by skjalgsm** [comment]
Yes. I made one for you :)
https://github.com/agens-no/iMessageStickerUnity/blob/master/iMessageStickerUnity18_10_2017.unitypackage

**Comment by JohannesDeml** [comment]
Just as a side note, you can use the release section of your repo to upload the packages. That way the release will be tagged in git and the package does not fill up the gitrepo. Releases are here: https://github.com/agens-no/iMessageStickerUnity/releases

**Comment by skjalgsm** [comment]
Ah thanks, good to know =)
