### ISSUE TITLE
Unable to build to xcode

### ISSUE THREAD

**Issue by lovaharrison** [agens-no/iMessageStickerUnity#19]
Hello,
Thank you very much for this plugin.
But I am unable to create a build to xcode, I get this error: "System.Net.WebException : The remote server returned an error . (401) Unauthorized".
Could you help? 
Also, is there any tutorial on how to use your plugin but the readme?

**Comment by skjalgsm** [comment]
I’m afraid not. Do you have any more info to provide with your error? Theres not really any net code in the plugin so a webexception is a bit perplexing. Could you perhaps provide your log file?

**Comment by lovaharrison** [comment]
Realy sorry, It was another plugin that caused it. 
I managed to make things work properly, 
Thank you.
