### ISSUE TITLE
Getting Invalid iMessage App from iTunes Connect

### ISSUE THREAD

**Issue by y3102sof** [agens-no/iMessageStickerUnity#23]
Hello,

I received an e-mail from iTunes Connect and it won't let me upload my app. It's because below reason.

"Invalid iMessage App - Your iMessage app contains an invalid sticker pack. The app may have been built or signed with non-compliant or prerelease tools. For more information, go to developer.apple.com."

I researched about it, but I cannot find clear solution. Do you have any suggestion? Please help.

**Comment by skjalgsm** [comment]
What does it look like when you open Xcode and what version of Xcode are you using?

**Comment by y3102sof** [comment]
I'm using 9.1 version of Xcode. I attached screenshots for Xcode. If you need more information, let me know.

![xcode](https://user-images.githubusercontent.com/11284456/33876683-82d3917c-df69-11e7-87db-9553f46dd5bc.png)
![xcodesticker](https://user-images.githubusercontent.com/11284456/33876686-85d78e14-df69-11e7-8075-753daa9ebfeb.png)

**Comment by skjalgsm** [comment]
This all looks good.

I haven't tried to publish in a while, myself, but could you do me a favor and click the small arrow button in the bottom right of your second screenshot? (Its the one so that you can view the app icons).

Is there anything missing there? Like maybe the newly required 1024pt App Store icon? If so, can you add a 1024 icon to that slot and try again?

**Comment by y3102sof** [comment]
Sorry for late reply. I added 1024pt app store icon, then tried to upload but same result. Still working on how to fix it. Any idea?

**Comment by y3102sof** [comment]
I fixed it. I don't know why but if I build and upload by archive, everything goes well. Thanks for your support anyway.

**Comment by evgeny-detkov** [comment]
Hello! I have a similar situation: "Invalid iMessage App - Your iMessage app contains an invalid sticker pack. .... "
I use Unity 5.6.1f1, xcode 9.2.
The build is automated through teamcity.
The screenshots from this question fit my case one on one.
bundleId my application in a format, for example, com.company.app
bundleId project with stickers - com.company.app.stickers
In developer.apple.com two provisioned profiles were created and two AppsID for bundleId .
Sticker files are named as sticker_01.png, sticker_02.png, etc.
IMessage App icons are all correctly installed.
The Unity project for the test is empty, only the stickers and your iMessageStickerUnity-plugin have been added.
What else can you do and check? Help me, please.
