### ISSUE TITLE
[Feature Request] Using in-game-generated GIF/APNG?

### ISSUE THREAD

**Issue by sweatyc** [agens-no/iMessageStickerUnity#24]
Thanks for the great plugin, it saved us lot of times!

I would also wanna know is that possible to use in-game dynamically generated GIF/APNG, in stickers? Just like "Steppy Pants" which can record a 3s customized animation of your characters and use that in iMessage.

**Comment by skjalgsm** [comment]
Hey there, thanks for using the plugin =)

Unfortunately the plugin is really "dumb and contains no code". So all it
does is list the pre defined images in a sticker view.
