### ISSUE TITLE
Resources Folder Dependency

### ISSUE THREAD

**Issue by fenderrio** [agens-no/iMessageStickerUnity#26]
Hi,
Firstly, thanks very much for making this plugin and sharing it! It's been a real time saver, and the workflow is very simple and easy to follow. :)

We've had to make a few small tweaks to the code to make it suit our needs though;

- Most importantly, the plugin currently stores the Stickers.asset ScriptableObject in the **Resources** folder, which means that all the Sticker and Icon textures get pulled into the main Unity game build (even for Android!), which bloats the build unnecessarily.
On quick inspection, it seemed the only reason for it being in the Resources folder was to allow easy access to it from the Editor scripts. Therefore, we switched to using the 'Editor Default Resources' folder to get the same results, without the inclusion of assets in the Unity build.

- Secondly, something that someone else has already flagged; the builds were being hardcoded to CODE_SIGN_IDENTITY 'iPhone Distribution', which was causing Xcode to freak out about our provisioning profile. We change it to set to 'iPhone Developer'.

Hope this helps!
Thanks again,
Tom

**Comment by skjalgsm** [comment]
This is a very good issue. Editor Default Resources is a better place to put it. Could you submit a PR with this change or do you want me to change this?

**Comment by skjalgsm** [comment]
I went ahead and implemented the changes you requested. Could you do me the favor and look at the changes to see if they are what you expected?

https://github.com/agens-no/iMessageStickerUnity/commit/244ae4137ec4b7211055689702bef1f1a082bb9e

**Comment by fenderrio** [comment]
Hi,
Just checked out your commit, and that's pretty much exactly the same as the change we made :) nice one.
Cheers,
Tom
