### ISSUE TITLE
PBXProject.cs - RecursivelyCopy does not work on Windows 

### ISSUE THREAD

**Issue by hbaInfinity** [agens-no/iMessageStickerUnity#32]
I've just been tracking down a problem with adding Stickers to our iOS builds. I found that the structure of the Stickers project was not correct in the xCode Project, to which I have tracked down the problem to the RecursivelyCopy function. On Windows, the **Directory.GetDirectories()** function returns the path back with back slashes instead of forward slashes, making the recursive part fail when searching for the LastIndexOf the forward slash.

Ensuring the path only uses forward slashes make the code work again as intended.

**Comment by skjalgsm** [comment]
fixed in https://github.com/agens-no/iMessageStickerUnity/commit/9167e788da31b9e5c8e04d0530c32228b22973f7
