### ISSUE TITLE
Stickers are not sorted

### ISSUE THREAD

**Issue by Asorano** [agens-no/iMessageStickerUnity#38]
Hey,
I have added a bunch of stickers, sorted them in the StickerPack asset and also checked the index of each sticker. Additionally the image names start with the index too. Unfortunately the iMessage app shows them in a random order.

Is there any way to sort them?

Thanks!

**Comment by skjalgsm** [comment]
Hi Asorano.

The sticker pack exports the stickers in the same order that you set them up in Unity. What might have happened to you is that you made a build (which exports the sticker target to your xcode) with the wrong order, then you fixed the order in unity and did another build. But what happens now is that the exporter checks to see if you already have a sticker target in your xcode project and if it does it just skips exporting it again.

So could you try to open up xcode and remove the sticker pack manually before exporting again?

**Comment by Asorano** [comment]
Hey Skjalgsm,
thanks for your fast answer! I deleted the xcode project and started a new build but unfortunately it still has the same random order.
Do you have any other idea what could go wrong?

Thanks for your help!

**Comment by alexanderperrin** [comment]
Hey there! I'm absolutely loving the tool, though I'm having the same issue. The stickers appear to sort alphabetically and not in the sort order that appears in the inspector editor. After some investigation I've found that there's no Contents.json being written to Stickers.xcassets/Sticker Pack.stickerpack which is required for manual ordering. Currently looking into a solution. Thanks!

**Comment by Asorano** [comment]
Hey Alex,
after your post I checked the pull requests and there is one which adds the missing file:
https://github.com/handcircus/iMessageStickerUnity

I just checked it and it works perfectly! So thanks for your hint 👯‍♂️ 

@Skjalgsm Please take a look and apply the fix to your repo!
Thanks for your great tool btw!

**Comment by alexanderperrin** [comment]
I wish I had seen that! I just wrote the very same change myself. See #37 for previous PR.

**Comment by skjalgsm** [comment]
Done. Thanks for testing the PR and condirming it worked :)
