### ISSUE TITLE
My Game is not loading...

### ISSUE THREAD

**Issue by amit232git** [agens-no/iMessageStickerUnity#6]
Hi,

When i integrate this library, with my game, , everything is done successfully run from Xcode 8.2.1, but when game is not loading, then i have close game, and again start game the it is working fine.

And all configure stickers are in iMessage i can show and use. But that animated sequence sticker isn't work in iMessage.

Thank you
Amit

**Comment by skjalgsm** [comment]
Hi Amit, sorry to hear that. Are you sure the sticker sequence images are the correct size? Please run the editor test runner and see if it displays any errors. https://docs.unity3d.com/Manual/testing-editortestsrunner.html

**Comment by amit232git** [comment]
Hi ,

Thank you for your replay, i have not put correct size sticker, i am using the images of stickers from existing game assests.  Ok let me check with correct size sitcker and check.

Thank you
Amit
