### ISSUE TITLE
Xcode error

### ISSUE THREAD

**Issue by Sly88** [agens-no/iMessageStickerUnity#9]
Hi, 
I have one problem with iMessageStickerUnity. When I added your plugin into my project I get few errors in Xcode 

Signing for "Unity-iPhone-Stickers" requires a development team. Select a development team in the project editor.
Code signing is required for product type 'App Extension' in SDK 'iOS 10.2'

Do you have any idea what I doing wrong?

btw. when I added stickers via Xcode everything works well

Xcode File/New/Target/Sticker Pack Extension

**Comment by skjalgsm** [comment]
Hi, yes, you haven't specified the team in signing settkngs for the iMessage target. Sknply open the xcode project in xcode and you should see it marked as red.

**Comment by Sly88** [comment]
Hi, Thanks for your prompt response
I set the team in general section, do you have any suggestion?

**Comment by skjalgsm** [comment]
Could you post a screenshot of your xcode?

**Comment by Sly88** [comment]
[image: Inline image 1]

**Comment by Sly88** [comment]
Hi, How are you today?

Any news about my issues?
Do you need more details from Xcode?

Best,

**Comment by skjalgsm** [comment]
Hi. I still can't see the image you've uploaded. But here's a screenshot from my xcode with what I think you have to do.

1. Select the stickers target.
2. Select Build Settings
3. Search for Signing
4. Change the Development Team to your development team.

![image](https://cloud.githubusercontent.com/assets/568589/24653621/d87a8a80-1936-11e7-83b4-4f5024e619a1.png)

**Comment by chlgithub8** [comment]
Great! Thanks!
